[package]
name = "fasm-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap =  { version = "4.5.1", features = ["derive"] }
colored = "2.1.0"
faerie = "0.16.0"
target-lexicon = "0.11.2"
